# Generated by Django 4.1.3 on 2022-11-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='image',
            new_name='images',
        ),
    ]
