# Generated by Django 4.1.3 on 2022-11-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_catagory_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='images',
            new_name='image',
        ),
    ]
